# Generated by Django 5.0.7 on 2024-09-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frame_idx', models.TextField()),
                ('video_idx', models.TextField()),
            ],
        ),
    ]
