# Generated by Django 5.0.7 on 2024-08-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_frame_frame_name_video_video_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frame_path',
            field=models.FileField(upload_to='metadata/frames/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(upload_to='metadata/videos/'),
        ),
    ]
